"""Wrap the overlay in a minimal .app so macOS will grant it the camera.

`camera_status()` returned 0 — not determined — forever, and
`request_camera()` came back refused in about 100 ms, far too fast for a prompt
anyone could answer. `permission.py` was not the problem: **macOS will not show
a camera prompt to a process with no app bundle.** A bare Python process has no
`CFBundleIdentifier` and no `NSCameraUsageDescription`, so there is nothing to
put in the dialog and the request is declined before it is ever shown.

This builds the smallest bundle that fixes it. No Xcode, no signing, no Apple
Developer account — a `.app` is a directory with an `Info.plist`.

## Why the interpreter is copied in

TCC attributes permission to the bundle containing the running executable, so
the Python that asks for the camera has to live inside `Contents/MacOS/`. A
symlink is not enough: macOS resolves it and the association is lost with it.

## Why the packages are NOT linked in

The first version linked `Contents/lib` at the virtualenv so the copied
interpreter could find its packages. It worked, and the camera was still
refused, because a bundle is signed as a sealed unit:

    KAVACH.app: invalid destination for symbolic link in bundle
    file modified: KAVACH.app/Contents/lib

macOS rejects a bundle whose symlinks escape it, the signature never
validates, and TCC declines a bundle whose signature does not validate —
without ever showing a prompt, which is exactly the 100 ms refusal that made
this look like broken hardware in the first place.

So nothing points out of the bundle. The launcher exports `PYTHONPATH` at the
virtualenv's `site-packages` instead: an environment variable is not part of
the seal, so the signature stays valid and the imports still resolve.

**The bundle must be ad-hoc signed** (`codesign --sign -`, no certificate and
no Apple account) or the usage strings are not trusted. `build()` does it.
"""

from __future__ import annotations

import logging
import os
import plistlib
import shutil
import stat
import subprocess
import sys
from pathlib import Path

log = logging.getLogger("kavach.presence.appbundle")

BUNDLE_ID = "com.krishna.kavach.overlay"
APP_NAME = "KAVACH"

DEFAULT_LOCATION = Path.home() / "Applications"

#: Shown verbatim in the macOS permission dialogs. Written to be read by the
#: person deciding, not by a developer: it says what is captured and what
#: happens to it, because "KAVACH would like to access the camera" with no
#: reason is how people learn to click Deny.
CAMERA_REASON = (
    "KAVACH reads hand gestures from the webcam to confirm or cancel actions. "
    "Frames are processed on this Mac and never saved or sent anywhere."
)
MICROPHONE_REASON = (
    "KAVACH listens for its wake word and your spoken commands. Audio is "
    "transcribed on this Mac and never saved or sent anywhere."
)


def _base_python_home() -> Path:
    """Where the real interpreter's standard library lives.

    The copied binary has no idea. uv builds it with a compiled-in prefix of
    `/install`, so run outside its virtualenv it cannot find `encodings` and
    dies before executing a line. The venv records the answer in pyvenv.cfg's
    `home`; PYTHONHOME is how it is handed back.
    """
    cfg = Path(sys.prefix) / "pyvenv.cfg"
    for line in cfg.read_text().splitlines():
        if line.strip().startswith("home"):
            return Path(line.split("=", 1)[1].strip()).parent
    raise RuntimeError(f"no `home` in {cfg} — build from inside the venv.")


def _project_root() -> Path:
    """Where the `kavach` package actually lives.

    It is the project source, not something in site-packages, so it resolves
    from a shell only because the working directory happens to be on sys.path.
    Launch Services starts at `/`, and the app died with `No module named
    'kavach'` before writing a line — invisibly, because it also discards
    stderr.
    """
    import kavach

    return Path(kavach.__file__).resolve().parent.parent


def _launcher_script(module: str, site_packages: Path,
                     python_home: Path, project: Path) -> str:
    """The bundle's executable: exec the interpreter beside it.

    A shell script rather than the interpreter directly, because `open
    KAVACH.app` passes no arguments and would otherwise land you in an
    interactive Python. The interpreter it execs still lives inside
    Contents/MacOS, so the bundle association survives.

    Environment variables rather than a linked `lib`: they are not part of the
    code signature, so both the standard library and the packages resolve
    without a symlink escaping the bundle and breaking the seal.
    """
    return (
        "#!/bin/sh\n"
        "# Generated by kavach.presence.appbundle — do not edit.\n"
        "#\n"
        "# Environment, not symlinks: a link out of the bundle invalidates its\n"
        "# signature, and TCC silently refuses a bundle that fails to verify.\n"
        "#\n"
        "# PYTHONHOME is the standard library — the copied interpreter has a\n"
        "# compiled-in prefix of /install and cannot find `encodings` without\n"
        "# it. PYTHONPATH is this project's packages.\n"
        'here="$(cd "$(dirname "$0")" && pwd)"\n'
        f'PYTHONHOME="{python_home}"\n'
        f'PYTHONPATH="{project}:{site_packages}"'
        '"${PYTHONPATH:+:$PYTHONPATH}"\n'
        "export PYTHONHOME PYTHONPATH\n"
        "\n"
        "# Launch Services discards stdout and stderr, so a failure under\n"
        "# `open -a` leaves no trace at all — which is indistinguishable from\n"
        "# the app starting and quietly doing nothing.\n"
        'logdir="$HOME/.kavach/logs"\n'
        'mkdir -p "$logdir"\n'
        f'exec "$here/python3" -m {module} "$@" '
        '>>"$logdir/overlay.out" 2>&1\n'
    )


def build(location: Path | None = None, module: str = "kavach.presence") -> Path:
    """Create (or replace) KAVACH.app and return its path."""
    location = Path(location) if location else DEFAULT_LOCATION
    location.mkdir(parents=True, exist_ok=True)
    app = location / f"{APP_NAME}.app"

    if app.exists():
        shutil.rmtree(app)

    contents = app / "Contents"
    macos = contents / "MacOS"
    macos.mkdir(parents=True, exist_ok=True)

    venv = Path(sys.prefix)
    interpreter = Path(sys.executable)

    # The interpreter itself, copied. See the module docstring for why not a
    # symlink and why this does not break imports.
    shutil.copy2(interpreter, macos / "python3")

    site_packages = next(
        (p for p in map(Path, sys.path)
         if p.name == "site-packages" and str(p).startswith(str(venv))),
        None,
    )
    if site_packages is None:
        raise RuntimeError(
            "could not find site-packages — build this from inside the "
            "project virtualenv (uv run kavach-app)."
        )

    launcher = macos / APP_NAME
    launcher.write_text(
        _launcher_script(module, site_packages, _base_python_home(),
                         _project_root()))
    launcher.chmod(launcher.stat().st_mode | stat.S_IEXEC | stat.S_IXGRP
                   | stat.S_IXOTH)

    plist = {
        "CFBundleIdentifier": BUNDLE_ID,
        "CFBundleName": APP_NAME,
        "CFBundleDisplayName": APP_NAME,
        "CFBundleExecutable": APP_NAME,
        "CFBundlePackageType": "APPL",
        "CFBundleShortVersionString": "1.0",
        "CFBundleVersion": "1",
        # An agent: the orb is a floating panel, not a windowed app, and a
        # Dock icon for it would be noise.
        "LSUIElement": True,
        "NSCameraUsageDescription": CAMERA_REASON,
        "NSMicrophoneUsageDescription": MICROPHONE_REASON,
        "NSHighResolutionCapable": True,
    }
    with (contents / "Info.plist").open("wb") as handle:
        plistlib.dump(plist, handle)

    # Ad-hoc signed, or the usage strings are not trusted and the prompt is
    # never shown. `-` means no certificate: no Apple account is involved.
    signed = subprocess.run(
        ["codesign", "--force", "--sign", "-", str(app)],
        capture_output=True, text=True,
    )
    if signed.returncode != 0:
        raise RuntimeError(
            f"could not sign the bundle:\n{signed.stderr.strip()[:400]}"
        )

    verified = subprocess.run(
        ["codesign", "--verify", "--strict", str(app)],
        capture_output=True, text=True,
    )
    if verified.returncode != 0:
        # Reported, not shrugged off: an unverifiable bundle is refused by TCC
        # without a prompt, which reads as a broken camera.
        raise RuntimeError(
            f"the bundle does not verify, so macOS will refuse it:\n"
            f"{verified.stderr.strip()[:400]}"
        )

    log.info("built and signed %s", app)
    return app


def describe(app: Path) -> dict:
    """Read back what was built, for the CLI and for tests."""
    try:
        with (app / "Contents" / "Info.plist").open("rb") as handle:
            info = plistlib.load(handle)
    except Exception:
        return {}
    return info


def main(argv: list[str] | None = None) -> int:
    import argparse

    parser = argparse.ArgumentParser(
        description="Build the KAVACH.app wrapper that lets macOS grant the "
                    "camera.")
    parser.add_argument("--to", default=None,
                        help=f"where to put it (default: {DEFAULT_LOCATION})")
    args = parser.parse_args(argv)

    try:
        app = build(Path(args.to) if args.to else None)
    except Exception as exc:
        print(f"✗ {exc}", file=sys.stderr)
        return 1

    info = describe(app)
    print(f"\n  built {app}")
    print(f"    bundle id : {info.get('CFBundleIdentifier')}")
    print(f"    camera    : {'yes' if info.get('NSCameraUsageDescription') else 'MISSING'}")
    print(f"    mic       : {'yes' if info.get('NSMicrophoneUsageDescription') else 'MISSING'}")
    print("\n  Start the orb through it so macOS can prompt:")
    print(f"    open -a {app}")
    print("\n  macOS asks once. Answer Allow, and gestures come alive —")
    print("  press G in the panel, then hold ✌️ for 0.8s to start a turn.\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
